### ISSUE TITLE
cannot find controller outline.

### ISSUE THREAD

**Issue by luku756** [dag10/HoloViveObserver#13]
I build and run with hololens, vive.

sound say,
searching for vr invironment.
connected.
move controller to controller outline and poll the triger.

but i cant find controller outline.
i spin my head round and round, i cant find it.

I see controllerTargetPrefab variable in AlignmentClient class. this is controller model? but it's just define and use. i cant find insert data.

i use unity 2017.1.1f1. 
please help!

**Comment by dag10** [comment]
Instead of just turning around, turn around and then take a step back. It's
supposed to appear in the middle of where your head *was* when the app was
launched.

**Comment by luku756** [comment]
Oh, thanks!
I was never think about that.

this project perfectly work for me.
