### ISSUE TITLE
[SOLVED] Unity Generates Invalid Solution - Invalid Project References

### ISSUE THREAD

**Issue by nsheahandev** [dag10/HoloViveObserver#3]
After loading the scene into Unity (v5.5.0f3) and going through the build process, my visual studio solution has invalid file references to the "Assembly-CSharp" and "Assembly-CSharp-firstpass" projects.

The solution is looking for these projects under "C:\Users\Drew\Projects\HoloViveObserver\HoloViveObserver\App\GeneratedProjects\UWP\Assembly-CSharp-firstpass\Assembly-CSharp-firstpass.csproj".
![absolutefilepathissue](https://cloud.githubusercontent.com/assets/10697977/22896106/da828dc6-f1ec-11e6-906b-4d7c3c48c3ba.png)

This file path does not exist on my file system and I am wondering what build assets I need to reconfigure in order to build the solution correctly. I have almost no Unity experience.

Thank you very much,
     Nicholas Sheahan

**Comment by dag10** [comment]
Hi,

My bad on that one. Delete the App folder, create a new, empty App folder, and follow the build instructions in the readme. Sorry about that. 

Drew

**Comment by nsheahandev** [comment]
Works great! Thank you very much.
