### ISSUE TITLE
[SOLVED] HoloLens not rendering holograms

### ISSUE THREAD

**Issue by jimmybond** [dag10/HoloViveObserver#4]
Awesome project!

Just an FYI if anyone has the same issue rendering holograms on the HoloLens.

I couldn't view any holograms (even the 'Made in Unity' splash screen when the application starts). I used visual studio to debug the HoloLens application remotely which produced this error:

****************
Graphics.CopyTexture could not find destination D3D11 texture object. Maybe it is a RenderTexture that is not created yet?

(Filename: C:\buildslave\unity\build\Runtime/GfxDevice/d3d11/GfxDeviceD3D11.cpp Line: 1765)
****************

A simple fix is to change the color space setting to Gamma. It's located in player settings -> other settings -> Rendering

**Comment by nsheahandev** [comment]
I'm having this issue as well. I'm unable to locate the color settings you have mentioned. Where exactly are they in the Unity interface?

**Comment by jimmybond** [comment]
Edit -> project settings -> player
On the right side of Unity in the inpector you should see player settings.
Then open the 'other settings' tab. There you'll find the color space setting.


![player settings](https://cloud.githubusercontent.com/assets/25780454/22996285/fefca2b6-f419-11e6-8f37-a092649cdecf.PNG)

**Comment by nsheahandev** [comment]
Thank you @jimmybond
